// Package codex - Codex CLI 配置管理 - 配置代理连接和模型提供商
// Copyright (c) 2026 fooyii.
// Created: 2026-05-22

package codex

import (
	"fmt"
	"os"
	"path/filepath"
)

const (
	configDir    = ".codex"
	configFile   = "config.toml"
	backupSuffix = ".chat2responses.bak"
)

type SetupConfig struct {
	Model   string
	BaseURL string
	APIKey  string
	WireAPI string
}

var DefaultSetup = SetupConfig{
	WireAPI: "responses",
}

func configPath() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("home dir: %w", err)
	}
	return filepath.Join(home, configDir, configFile), nil
}

func Setup(cfg SetupConfig) error {
	path, err := configPath()
	if err != nil {
		return err
	}

	if _, err := os.Stat(path); err == nil {
		backup := path + backupSuffix
		data, err := os.ReadFile(path)
		if err != nil {
			return fmt.Errorf("read existing config: %w", err)
		}
		if err := os.WriteFile(backup, data, 0644); err != nil {
			return fmt.Errorf("backup config: %w", err)
		}
		fmt.Printf("Backed up existing config to %s\n", backup)
	}

	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("create config dir: %w", err)
	}

	content := fmt.Sprintf(`# Generated by chat2responses setup
model = "%s"
model_provider = "chat2responses"

[model_providers.chat2responses]
base_url = "%s/v1"
env_key = "CODEX_API_KEY"
wire_api = "%s"
`, cfg.Model, cfg.BaseURL, cfg.WireAPI)

	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		return fmt.Errorf("write config: %w", err)
	}

	fmt.Printf("Codex configuration written to %s\n", path)
	fmt.Println("Make sure to set CODEX_API_KEY environment variable")
	if cfg.APIKey != "" {
		fmt.Printf("Run: export CODEX_API_KEY=\"%s\"\n", cfg.APIKey)
	} else {
		fmt.Println("Run: export CODEX_API_KEY=your-api-key")
	}
	fmt.Println()
	fmt.Println("You can now run: codex")

	return nil
}

func Restore() error {
	path, err := configPath()
	if err != nil {
		return err
	}

	backup := path + backupSuffix
	if _, err := os.Stat(backup); os.IsNotExist(err) {
		return fmt.Errorf("no backup found at %s", backup)
	}

	data, err := os.ReadFile(backup)
	if err != nil {
		return fmt.Errorf("read backup: %w", err)
	}

	if err := os.WriteFile(path, data, 0644); err != nil {
		return fmt.Errorf("restore config: %w", err)
	}

	if err := os.Remove(backup); err != nil {
		return fmt.Errorf("remove backup: %w", err)
	}

	fmt.Println("Restored Codex configuration from backup")
	return nil
}

func HasBackup() bool {
	path, err := configPath()
	if err != nil {
		return false
	}
	_, err = os.Stat(path + backupSuffix)
	return err == nil
}

func Status() (string, error) {
	path, err := configPath()
	if err != nil {
		return "", err
	}

	if _, err := os.Stat(path); os.IsNotExist(err) {
		return fmt.Sprintf("No Codex config found at %s\n", path), nil
	}

	data, _ := os.ReadFile(path)
	hasBackup := HasBackup()

	status := fmt.Sprintf("Codex config: %s\n%s\n", path, string(data))
	if hasBackup {
		status += "Backup available (use 'chat2responses restore' to revert)\n"
	} else {
		status += "No backup available\n"
	}

	return status, nil
}


func IsConfigured() bool {
	path, err := configPath()
	if err != nil {
		return false
	}
	_, err = os.Stat(path)
	return err == nil
}

