// Author: fooyii, Email: fooyii@icloud.com, Date: 2026-06-13
// codex: max-lines(430)
// Package codex - Codex CLI 配置管理 - 配置代理连接和模型提供商
// Copyright (c) 2026 fooyii.
// Created: 2026-05-22

package codex

import (
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"strings"
)

const (
	configDir    = ".codex"
	configFile   = "config.toml"
	backupSuffix = ".chat2responses.bak"
)

type SetupConfig struct {
	Model        string
	BaseURL      string
	APIKey       string
	WireAPI      string
	CustomModels []string
}

var DefaultSetup = SetupConfig{
	WireAPI: "responses",
}

func configPath() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("home dir: %w", err)
	}
	return filepath.Join(home, configDir, configFile), nil
}

func Setup(cfg SetupConfig) error {
	path, err := configPath()
	if err != nil {
		return err
	}

	if _, err := os.Stat(path); err == nil {
		backup := path + backupSuffix
		data, err := os.ReadFile(path)
		if err != nil {
			return fmt.Errorf("read existing config: %w", err)
		}
		if err := os.WriteFile(backup, data, 0644); err != nil {
			return fmt.Errorf("backup config: %w", err)
		}
		fmt.Printf("Backed up existing config to %s\n", backup)
	}

	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("create config dir: %w", err)
	}

	var modelsLine string
	if len(cfg.CustomModels) > 0 {
		var quoted []string
		for _, m := range cfg.CustomModels {
			quoted = append(quoted, fmt.Sprintf(`"%s"`, m))
		}
		modelsLine = fmt.Sprintf("\nmodels = [%s]", strings.Join(quoted, ", "))
	}

	content := fmt.Sprintf(`# Generated by chat2responses setup
model = "%s"
model_provider = "custom"

[model_providers.custom]
name = "chat2responses"
base_url = "%s/v1"
env_key = "CODEX_API_KEY"
wire_api = "%s"
requires_openai_auth = true%s
`, cfg.Model, cfg.BaseURL, cfg.WireAPI, modelsLine)

	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		return fmt.Errorf("write config: %w", err)
	}

	fmt.Printf("Codex configuration written to %s\n", path)
	fmt.Println("Make sure to set CODEX_API_KEY environment variable")
	if cfg.APIKey != "" {
		fmt.Printf("Run: export CODEX_API_KEY=\"%s\"\n", cfg.APIKey)
	} else {
		fmt.Println("Run: export CODEX_API_KEY=your-api-key")
	}
	fmt.Println()
	fmt.Println("You can now run: codex")

	return nil
}

func Restore() error {
	path, err := configPath()
	if err != nil {
		return err
	}

	backup := path + backupSuffix
	if _, err := os.Stat(backup); os.IsNotExist(err) {
		return fmt.Errorf("no backup found at %s", backup)
	}

	data, err := os.ReadFile(backup)
	if err != nil {
		return fmt.Errorf("read backup: %w", err)
	}

	if err := os.WriteFile(path, data, 0644); err != nil {
		return fmt.Errorf("restore config: %w", err)
	}

	if err := os.Remove(backup); err != nil {
		return fmt.Errorf("remove backup: %w", err)
	}

	fmt.Println("Restored Codex configuration from backup")
	return nil
}

func HasBackup() bool {
	path, err := configPath()
	if err != nil {
		return false
	}
	_, err = os.Stat(path + backupSuffix)
	return err == nil
}

func Status() (string, error) {
	path, err := configPath()
	if err != nil {
		return "", err
	}

	if _, err := os.Stat(path); os.IsNotExist(err) {
		return fmt.Sprintf("No Codex config found at %s\n", path), nil
	}

	data, _ := os.ReadFile(path)
	hasBackup := HasBackup()

	status := fmt.Sprintf("Codex config: %s\n%s\n", path, string(data))
	if hasBackup {
		status += "Backup available (use 'chat2responses restore' to revert)\n"
	} else {
		status += "No backup available\n"
	}

	return status, nil
}

func IsConfigured() bool {
	path, err := configPath()
	if err != nil {
		return false
	}
	_, err = os.Stat(path)
	return err == nil
}

// AutoCheckAndFix automatically verifies whether the Codex CLI config is correct
// and matches the current proxy's port, model, and list of custom models, correcting it if needed.
func AutoCheckAndFix(serverPort int, currentModel string, apiKey string, customModels []string) error {
	path, err := configPath()
	if err != nil {
		slog.Debug("Skipping Codex CLI autocheck: home directory or config path not available", "error", err)
		return nil
	}

	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			slog.Info("Codex CLI configuration not found. Automatically setting up a correct one...", "path", path)
			return Setup(SetupConfig{
				Model:        currentModel,
				BaseURL:      fmt.Sprintf("http://127.0.0.1:%d", serverPort),
				APIKey:       apiKey,
				WireAPI:      "responses",
				CustomModels: customModels,
			})
		}
		return fmt.Errorf("read codex config: %w", err)
	}

	content := string(data)

	// Safe TOML extraction
	provider, baseURL, model, existingModels := parseCurrentProviderAndBaseURLAndModels(content)

	// Validate if it is already pointing to our proxy
	isExpectedBaseURL := (baseURL == fmt.Sprintf("http://127.0.0.1:%d/v1", serverPort) || baseURL == fmt.Sprintf("http://localhost:%d/v1", serverPort))

	// Check if custom models list matches exactly
	modelsMatch := true
	if len(customModels) != len(existingModels) {
		modelsMatch = false
	} else {
		existingMap := make(map[string]bool)
		for _, m := range existingModels {
			existingMap[m] = true
		}
		for _, m := range customModels {
			if !existingMap[m] {
				modelsMatch = false
				break
			}
		}
	}

	if provider == "custom" && isExpectedBaseURL && model == currentModel && modelsMatch {
		slog.Info("Codex CLI configuration is correct and verified", "path", path)
		return nil
	}

	slog.Warn("Codex CLI config mismatch or outdated custom models. Performing non-destructive auto-heal...",
		"path", path,
		"current_provider", provider,
		"current_base_url", baseURL,
		"current_model", model,
	)

	// Perform backup before modification
	backup := path + backupSuffix
	if err := os.WriteFile(backup, data, 0644); err != nil {
		slog.Warn("Failed to create backup of Codex configuration", "error", err)
	} else {
		slog.Info("Backed up existing config", "path", backup)
	}

	// Non-destructive update
	newContent := nonDestructiveUpdate(content, serverPort, currentModel, customModels)

	if err := os.WriteFile(path, []byte(newContent), 0644); err != nil {
		return fmt.Errorf("write updated codex config: %w", err)
	}

	slog.Info("Successfully performed non-destructive auto-heal on Codex config", "path", path)
	return nil
}

func parseCurrentProviderAndBaseURLAndModels(content string) (provider string, baseURL string, model string, models []string) {
	lines := strings.Split(content, "\n")

	// 第一轮遍历：查找当前处于激活状态的服务商与模型
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "#") {
			continue
		}
		parts := strings.SplitN(trimmed, "=", 2)
		if len(parts) == 2 {
			key := strings.TrimSpace(parts[0])
			val := strings.Trim(strings.TrimSpace(parts[1]), `"'`+"`"+`"`)
			if key == "model_provider" {
				provider = val
			} else if key == "model" {
				model = val
			}
		}
	}

	if provider == "" {
		return "", "", model, nil
	}

	// 第二轮遍历：查找指定服务商的 base_url 以及 models 列表
	inTargetProvider := false
	targetHeader := fmt.Sprintf("[model_providers.%s]", provider)
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "#") {
			continue
		}
		if strings.HasPrefix(trimmed, "[") && strings.HasSuffix(trimmed, "]") {
			if trimmed == targetHeader {
				inTargetProvider = true
			} else {
				inTargetProvider = false
			}
			continue
		}
		if inTargetProvider {
			parts := strings.SplitN(trimmed, "=", 2)
			if len(parts) == 2 {
				key := strings.TrimSpace(parts[0])
				val := strings.TrimSpace(parts[1])
				if key == "base_url" {
					baseURL = strings.Trim(val, `"'`+"`"+`"`)
				} else if key == "models" {
					arrStr := val
					if strings.HasPrefix(arrStr, "[") && strings.HasSuffix(arrStr, "]") {
						arrStr = arrStr[1 : len(arrStr)-1]
						for _, item := range strings.Split(arrStr, ",") {
							item = strings.Trim(strings.TrimSpace(item), `"'`+"`"+`"`)
							if item != "" {
								models = append(models, item)
							}
						}
					}
				}
			}
		}
	}

	return provider, baseURL, model, models
}

func nonDestructiveUpdate(content string, serverPort int, currentModel string, customModels []string) string {
	lines := strings.Split(content, "\n")
	hasModelProvider := false
	hasModel := false

	for i, line := range lines {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "#") {
			continue
		}
		parts := strings.SplitN(trimmed, "=", 2)
		if len(parts) == 2 {
			key := strings.TrimSpace(parts[0])
			if key == "model_provider" {
				lines[i] = `model_provider = "custom"`
				hasModelProvider = true
			} else if key == "model" {
				lines[i] = fmt.Sprintf(`model = "%s"`, currentModel)
				hasModel = true
			}
		}
	}

	newContent := strings.Join(lines, "\n")
	if !hasModelProvider {
		newContent = `model_provider = "custom"` + "\n" + newContent
	}
	if !hasModel {
		newContent = fmt.Sprintf(`model = "%s"`, currentModel) + "\n" + newContent
	}

	// 检查是否存在 [model_providers.custom] 配置区块
	targetHeader := "[model_providers.custom]"

	var modelsStr string
	if len(customModels) > 0 {
		var quoted []string
		for _, m := range customModels {
			quoted = append(quoted, fmt.Sprintf(`"%s"`, m))
		}
		modelsStr = fmt.Sprintf("\nmodels = [%s]", strings.Join(quoted, ", "))
	}

	if !strings.Contains(newContent, targetHeader) {
		// Append the block at the end
		newContent = strings.TrimSpace(newContent) + "\n\n" + fmt.Sprintf(`[model_providers.custom]
name = "chat2responses"
base_url = "http://127.0.0.1:%d/v1"
env_key = "CODEX_API_KEY"
wire_api = "responses"
requires_openai_auth = true%s
`, serverPort, modelsStr)
	} else {
		// 在已存在的 [model_providers.custom] 配置区块内，精准更新 base_url、name、requires_openai_auth 以及 models
		lines = strings.Split(newContent, "\n")
		inBlock := false
		hasModels := false
		hasRequiresAuth := false
		for i, line := range lines {
			trimmed := strings.TrimSpace(line)
			if strings.HasPrefix(trimmed, "#") {
				continue
			}
			if strings.HasPrefix(trimmed, "[") && strings.HasSuffix(trimmed, "]") {
				if trimmed == targetHeader {
					inBlock = true
				} else {
					if inBlock {
						if !hasRequiresAuth {
							lines[i-1] = lines[i-1] + "\nrequires_openai_auth = true"
						}
						if !hasModels && modelsStr != "" {
							lines[i-1] = lines[i-1] + modelsStr
						}
					}
					inBlock = false
				}
				continue
			}
			if inBlock {
				parts := strings.SplitN(trimmed, "=", 2)
				if len(parts) == 2 {
					key := strings.TrimSpace(parts[0])
					if key == "base_url" {
						lines[i] = fmt.Sprintf(`base_url = "http://127.0.0.1:%d/v1"`, serverPort)
					} else if key == "name" {
						lines[i] = `name = "chat2responses"`
					} else if key == "requires_openai_auth" {
						lines[i] = `requires_openai_auth = true`
						hasRequiresAuth = true
					} else if key == "models" {
						if len(customModels) > 0 {
							var quoted []string
							for _, m := range customModels {
								quoted = append(quoted, fmt.Sprintf(`"%s"`, m))
							}
							lines[i] = fmt.Sprintf(`models = [%s]`, strings.Join(quoted, ", "))
						} else {
							lines[i] = ""
						}
						hasModels = true
					}
				}
			}
		}
		if inBlock {
			if !hasRequiresAuth {
				lines[len(lines)-1] = lines[len(lines)-1] + "\nrequires_openai_auth = true"
			}
			if !hasModels && modelsStr != "" {
				lines[len(lines)-1] = lines[len(lines)-1] + modelsStr
			}
		}
		newContent = strings.Join(lines, "\n")
	}

	return newContent
}

// SwitchProvider 切换 Codex 的 model_provider 和 model，实现一键在官方和自定义代理之间登录与使用。
func SwitchProvider(target string) error {
	path, err := configPath()
	if err != nil {
		return err
	}

	data, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("read codex config: %w", err)
	}

	content := string(data)
	lines := strings.Split(content, "\n")

	var newProvider string
	var newModel string
	if target == "official" || target == "openai" {
		newProvider = "openai"
		newModel = "gpt-4o"
	} else if target == "proxy" || target == "custom" {
		newProvider = "custom"
		newModel = "gpt-4o" // 默认模型，可由 AutoCheckAndFix 进行进一步校准
	} else {
		return fmt.Errorf("unknown provider target: %s, must be 'official' or 'proxy'", target)
	}

	hasModelProvider := false
	hasModel := false

	for i, line := range lines {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "#") {
			continue
		}
		parts := strings.SplitN(trimmed, "=", 2)
		if len(parts) == 2 {
			key := strings.TrimSpace(parts[0])
			if key == "model_provider" {
				lines[i] = fmt.Sprintf(`model_provider = "%s"`, newProvider)
				hasModelProvider = true
			} else if key == "model" {
				lines[i] = fmt.Sprintf(`model = "%s"`, newModel)
				hasModel = true
			}
		}
	}

	newContent := strings.Join(lines, "\n")
	if !hasModelProvider {
		newContent = fmt.Sprintf(`model_provider = "%s"`, newProvider) + "\n" + newContent
	}
	if !hasModel {
		newContent = fmt.Sprintf(`model = "%s"`, newModel) + "\n" + newContent
	}

	if err := os.WriteFile(path, []byte(newContent), 0644); err != nil {
		return fmt.Errorf("write codex config: %w", err)
	}

	return nil
}
