package codex

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestAutoCheckAndFix(t *testing.T) {
	// Create a temp directory to act as the fake user home
	tempDir, err := os.MkdirTemp("", "codex-test-home-*")
	if err != nil {
		t.Fatalf("failed to create temp dir: %v", err)
	}
	defer os.RemoveAll(tempDir)

	// Save original HOME and restore after test
	origHome := os.Getenv("HOME")
	os.Setenv("HOME", tempDir)
	defer os.Setenv("HOME", origHome)

	// 1. Verify AutoCheckAndFix creates a new config if none exists
	err = AutoCheckAndFix(8000, "gpt-4o", "fake-key")
	if err != nil {
		t.Fatalf("AutoCheckAndFix returned error: %v", err)
	}

	configFilePath := filepath.Join(tempDir, configDir, configFile)
	if _, err := os.Stat(configFilePath); os.IsNotExist(err) {
		t.Fatalf("expected config file to be created at %s, but it doesn't exist", configFilePath)
	}

	data, err := os.ReadFile(configFilePath)
	if err != nil {
		t.Fatalf("failed to read config file: %v", err)
	}

	content := string(data)
	if !strings.Contains(content, `model = "gpt-4o"`) {
		t.Errorf("expected config to contain model = \"gpt-4o\", got: %s", content)
	}
	if !strings.Contains(content, `base_url = "http://127.0.0.1:8000/v1"`) {
		t.Errorf("expected config to contain correct base_url, got: %s", content)
	}

	// 2. Modify config file to be incorrect (e.g. wrong model and port)
	incorrectContent := `# Generated by chat2responses setup
model = "gpt-3.5-turbo"
model_provider = "chat2responses"

[model_providers.chat2responses]
base_url = "http://127.0.0.1:9999/v1"
env_key = "CODEX_API_KEY"
wire_api = "responses"
`
	err = os.WriteFile(configFilePath, []byte(incorrectContent), 0644)
	if err != nil {
		t.Fatalf("failed to write incorrect config: %v", err)
	}

	// 3. Run AutoCheckAndFix and verify it corrects the file to matches current settings (port 8000, model gpt-4o)
	err = AutoCheckAndFix(8000, "gpt-4o", "fake-key")
	if err != nil {
		t.Fatalf("AutoCheckAndFix returned error: %v", err)
	}

	data, err = os.ReadFile(configFilePath)
	if err != nil {
		t.Fatalf("failed to read corrected config file: %v", err)
	}

	content = string(data)
	if !strings.Contains(content, `model = "gpt-4o"`) {
		t.Errorf("expected config to be corrected to contain gpt-4o, got: %s", content)
	}
	if !strings.Contains(content, `base_url = "http://127.0.0.1:8000/v1"`) {
		t.Errorf("expected config to be corrected to contain port 8000 base_url, got: %s", content)
	}
}
