// Package codex - Codex CLI 配置管理 - 配置代理连接和模型提供商
// Copyright (c) 2026 fooyii.
// Created: 2026-05-22

package codex

import (
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"strings"
)

const (
	configDir    = ".codex"
	configFile   = "config.toml"
	backupSuffix = ".chat2responses.bak"
)

type SetupConfig struct {
	Model   string
	BaseURL string
	APIKey  string
	WireAPI string
}

var DefaultSetup = SetupConfig{
	WireAPI: "responses",
}

func configPath() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("home dir: %w", err)
	}
	return filepath.Join(home, configDir, configFile), nil
}

func Setup(cfg SetupConfig) error {
	path, err := configPath()
	if err != nil {
		return err
	}

	if _, err := os.Stat(path); err == nil {
		backup := path + backupSuffix
		data, err := os.ReadFile(path)
		if err != nil {
			return fmt.Errorf("read existing config: %w", err)
		}
		if err := os.WriteFile(backup, data, 0644); err != nil {
			return fmt.Errorf("backup config: %w", err)
		}
		fmt.Printf("Backed up existing config to %s\n", backup)
	}

	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("create config dir: %w", err)
	}

	content := fmt.Sprintf(`# Generated by chat2responses setup
model = "%s"
model_provider = "chat2responses"

[model_providers.chat2responses]
name = "chat2responses"
base_url = "%s/v1"
env_key = "CODEX_API_KEY"
wire_api = "%s"
`, cfg.Model, cfg.BaseURL, cfg.WireAPI)

	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		return fmt.Errorf("write config: %w", err)
	}

	fmt.Printf("Codex configuration written to %s\n", path)
	fmt.Println("Make sure to set CODEX_API_KEY environment variable")
	if cfg.APIKey != "" {
		fmt.Printf("Run: export CODEX_API_KEY=\"%s\"\n", cfg.APIKey)
	} else {
		fmt.Println("Run: export CODEX_API_KEY=your-api-key")
	}
	fmt.Println()
	fmt.Println("You can now run: codex")

	return nil
}

func Restore() error {
	path, err := configPath()
	if err != nil {
		return err
	}

	backup := path + backupSuffix
	if _, err := os.Stat(backup); os.IsNotExist(err) {
		return fmt.Errorf("no backup found at %s", backup)
	}

	data, err := os.ReadFile(backup)
	if err != nil {
		return fmt.Errorf("read backup: %w", err)
	}

	if err := os.WriteFile(path, data, 0644); err != nil {
		return fmt.Errorf("restore config: %w", err)
	}

	if err := os.Remove(backup); err != nil {
		return fmt.Errorf("remove backup: %w", err)
	}

	fmt.Println("Restored Codex configuration from backup")
	return nil
}

func HasBackup() bool {
	path, err := configPath()
	if err != nil {
		return false
	}
	_, err = os.Stat(path + backupSuffix)
	return err == nil
}

func Status() (string, error) {
	path, err := configPath()
	if err != nil {
		return "", err
	}

	if _, err := os.Stat(path); os.IsNotExist(err) {
		return fmt.Sprintf("No Codex config found at %s\n", path), nil
	}

	data, _ := os.ReadFile(path)
	hasBackup := HasBackup()

	status := fmt.Sprintf("Codex config: %s\n%s\n", path, string(data))
	if hasBackup {
		status += "Backup available (use 'chat2responses restore' to revert)\n"
	} else {
		status += "No backup available\n"
	}

	return status, nil
}

func IsConfigured() bool {
	path, err := configPath()
	if err != nil {
		return false
	}
	_, err = os.Stat(path)
	return err == nil
}

// AutoCheckAndFix automatically verifies whether the Codex CLI config is correct
// and matches the current proxy's port and model, correcting it if it is incorrect.
func AutoCheckAndFix(serverPort int, currentModel string, apiKey string) error {
	path, err := configPath()
	if err != nil {
		return err
	}

	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			slog.Info("Codex CLI configuration not found. Automatically setting up a correct one...", "path", path)
			return Setup(SetupConfig{
				Model:   currentModel,
				BaseURL: fmt.Sprintf("http://127.0.0.1:%d", serverPort),
				APIKey:  apiKey,
				WireAPI: "responses",
			})
		}
		return fmt.Errorf("read codex config: %w", err)
	}

	content := string(data)

	// Safe TOML extraction
	provider, baseURL, model := parseCurrentProviderAndBaseURL(content)

	// Validate if it is already pointing to our proxy
	isExpectedBaseURL := false
	expectedBaseURLLine1 := fmt.Sprintf("http://127.0.0.1:%d/v1", serverPort)
	expectedBaseURLLine2 := fmt.Sprintf("http://localhost:%d/v1", serverPort)
	if baseURL == expectedBaseURLLine1 || baseURL == expectedBaseURLLine2 {
		isExpectedBaseURL = true
	}

	if provider != "" && isExpectedBaseURL && model == currentModel {
		slog.Info("Codex CLI configuration is correct and verified", "path", path)
		return nil
	}

	slog.Warn("Codex CLI config mismatch. Performing non-destructive auto-heal...",
		"path", path,
		"current_provider", provider,
		"current_base_url", baseURL,
		"current_model", model,
	)

	// Perform backup before modification
	backup := path + backupSuffix
	if err := os.WriteFile(backup, data, 0644); err != nil {
		slog.Warn("Failed to create backup of Codex configuration", "error", err)
	} else {
		slog.Info("Backed up existing config", "path", backup)
	}

	// Non-destructive update
	newContent := nonDestructiveUpdate(content, serverPort, currentModel)

	if err := os.WriteFile(path, []byte(newContent), 0644); err != nil {
		return fmt.Errorf("write updated codex config: %w", err)
	}

	slog.Info("Successfully performed non-destructive auto-heal on Codex config", "path", path)
	return nil
}

func parseCurrentProviderAndBaseURL(content string) (provider string, baseURL string, model string) {
	lines := strings.Split(content, "\n")
	
	// First pass: find active provider and model
	for _, line := range lines {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "#") {
			continue
		}
		if strings.HasPrefix(line, "model_provider") {
			parts := strings.SplitN(line, "=", 2)
			if len(parts) == 2 {
				provider = strings.Trim(strings.TrimSpace(parts[1]), `"'`)
			}
		}
		if strings.HasPrefix(line, "model") && !strings.Contains(line, "_provider") && !strings.Contains(line, "_reasoning") {
			parts := strings.SplitN(line, "=", 2)
			if len(parts) == 2 {
				model = strings.Trim(strings.TrimSpace(parts[1]), `"'`)
			}
		}
	}
	
	if provider == "" {
		return "", "", model
	}
	
	// Second pass: find base_url for that provider
	inTargetProvider := false
	targetHeader := fmt.Sprintf("[model_providers.%s]", provider)
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "#") {
			continue
		}
		if strings.HasPrefix(trimmed, "[") && strings.HasSuffix(trimmed, "]") {
			if trimmed == targetHeader {
				inTargetProvider = true
			} else {
				inTargetProvider = false
			}
			continue
		}
		if inTargetProvider && strings.HasPrefix(trimmed, "base_url") {
			parts := strings.SplitN(trimmed, "=", 2)
			if len(parts) == 2 {
				baseURL = strings.Trim(strings.TrimSpace(parts[1]), `"'`)
				break
			}
		}
	}
	
	return provider, baseURL, model
}

func nonDestructiveUpdate(content string, serverPort int, currentModel string) string {
	lines := strings.Split(content, "\n")
	hasModelProvider := false
	hasModel := false
	
	for i, line := range lines {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "model_provider") {
			lines[i] = `model_provider = "chat2responses"`
			hasModelProvider = true
		} else if strings.HasPrefix(trimmed, "model") && !strings.Contains(trimmed, "_provider") && !strings.Contains(trimmed, "_reasoning") {
			lines[i] = fmt.Sprintf(`model = "%s"`, currentModel)
			hasModel = true
		}
	}
	
	newContent := strings.Join(lines, "\n")
	if !hasModelProvider {
		newContent = `model_provider = "chat2responses"` + "\n" + newContent
	}
	if !hasModel {
		newContent = fmt.Sprintf(`model = "%s"`, currentModel) + "\n" + newContent
	}
	
	// Check if [model_providers.chat2responses] block exists
	targetHeader := "[model_providers.chat2responses]"
	if !strings.Contains(newContent, targetHeader) {
		// Append the block at the end
		newContent = strings.TrimSpace(newContent) + "\n\n" + fmt.Sprintf(`[model_providers.chat2responses]
name = "chat2responses"
base_url = "http://127.0.0.1:%d/v1"
env_key = "CODEX_API_KEY"
wire_api = "responses"
`, serverPort)
	} else {
		// Update the base_url and name inside the existing [model_providers.chat2responses] block
		lines = strings.Split(newContent, "\n")
		inBlock := false
		for i, line := range lines {
			trimmed := strings.TrimSpace(line)
			if strings.HasPrefix(trimmed, "[") && strings.HasSuffix(trimmed, "]") {
				if trimmed == targetHeader {
					inBlock = true
				} else {
					inBlock = false
				}
				continue
			}
			if inBlock && strings.HasPrefix(trimmed, "base_url") {
				lines[i] = fmt.Sprintf(`base_url = "http://127.0.0.1:%d/v1"`, serverPort)
			}
			if inBlock && strings.HasPrefix(trimmed, "name") {
				lines[i] = `name = "chat2responses"`
			}
		}
		newContent = strings.Join(lines, "\n")
	}
	
	return newContent
}
